"Usage: cubegui-config [OPTION]... COMMAND\n"
"\n"
"Commands:\n"
"  --cflags     prints additional compiler flags. They already contain\n"
"               the include flags\n"
"  --cppflags   prints the include flags for the Cube GUI headers\n"
"  --libs       prints the required libraries for linking\n"
"  --ldflags    prints the required linker flags\n"
"  --incldir    prints the directory for the Cube GUI headers\n"
"  --cc         prints the C compiler name\n"
"  --cxx        prints the C++ compiler name\n"
"  --features <FEATURE-CATEGORY>\n"
"               prints available features selected by <FEATURE-CATEGORY>.\n"
"               Available feature categories:\n"
"                * substrates\n"
"                * compressions\n"
"                * targets\n"
"  --help       prints this usage information\n"
"\n"
"  --version    prints the version number of the Cube Writer package and\n"
"  --cubegui-revision\n"
"               prints the revision number of the Cube Writer package\n"
"  --common-revision\n"
"               prints the revision number of the common package\n"
"  --interface-version\n"
"               prints the interface version number\n"
"  --config-summary\n"
"               prints the summary of the Cube GUI configuration \n"
"\n"
"Options:\n"
"  --target <TARGET>\n"
"               displays the requested information for the given <TARGET>.\n"
"               On non-cross compiling systems, the 'backend' target is ignored.\n"
"\n"
